### ISSUE TITLE
FW: GitHub Page build warning

### ISSUE THREAD

**Issue by VincentTam** [cambragol/ultima-IV-trinity#5]
![screenshot_2018-10-01-23-37-06](https://user-images.githubusercontent.com/5748535/46317503-76ff1500-c5d3-11e8-957e-a7203f5da73c.png)

Thanks for your interest in @staticmanlab.

Please kindly consider the suggested solutions in the email.

**Comment by cambragol** [comment]
I added the files in question to an archive. I think that should fix the warning.

@staticmanlab is working great! Thanks for your work on that. The bare bones sample helped me overcome issues I couldn't figure out when originally trying to set up staticman.

**Comment by VincentTam** [comment]
Without the help from @ntsim, who created Staticman PR 219, I *wouldn't* be able to setup the API server.  Therefore, he should take the most credit, apart from @staticmanapp.

I received two more copies of the *same* email for commits 2c8856df and e0ce6a83 at 0:50 and 0:51 respectively.  Thanks for fixing this so that GitHub didn't send me any more warning for e0ec983b.

**Comment by cambragol** [comment]
I have made multiple commits without any page build warnings, so it looks like the issue is solved.
